### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by zhigang1992** [steve3d/threejs-dash-docset#1]
Thanks for creating this, I was able to build the docset, but even though the index works,

![image](https://user-images.githubusercontent.com/1057756/96327183-f13f4c80-1069-11eb-8149-ca302c84103f.png)

the page won't load after selecting one.

![image](https://user-images.githubusercontent.com/1057756/96327175-dc62b900-1069-11eb-9cc7-b8aba7280258.png)

but somehow, the example ones works.?

![image](https://user-images.githubusercontent.com/1057756/96327188-04521c80-106a-11eb-971a-9a86d5ae5b9d.png)

I've spent quite some time one trying to figure out what's going on and failed. please take a look, much appreciated.

**Comment by steve3d** [comment]
it just simply won't work in dash. So I deploy the doc on my company's local server.

**Comment by steve3d** [comment]
and that's why I never created a pr to dash's user contribution.

**Comment by zhigang1992** [comment]
Ah, do you mean this is abandoned now?

Can you provide a bit more insight on why exactly cause the issue, I'd like to give it a bit more tries.

**Comment by steve3d** [comment]
因为threejs的文档内部不是直接用的URL链接, 多数的页面都是通过javascript来加载, 转换太麻烦
